"""Central configuration for the fake B1 simulator."""

NUM_AGENTS = 4

MAP_WIDTH = 100.0
MAP_HEIGHT = 100.0
GRID_WIDTH = 32
GRID_HEIGHT = 32

TICK_RATE = 10

MIN_DRONE_SPEED = 1.0
MAX_DRONE_SPEED = 2.5
MAX_TURN_RATE_DEG = 18.0
BATTERY_DRAIN_PER_TICK = 0.12
DETECTION_PROBABILITY = 0.35

AGENT_STATES = [
    "SEARCHING",
    "REOBSERVING",
    "RETURNING",
    "IDLE",
]

VALID_TASK_TYPES = {"FRONTIER", "REOBSERVE"}
